site_name: SOMA

pages:
  - 'Introduction': 'index.md'
  - 'Client Command Reference':
    - 'buckets':
      - 'property add': 'somaadm/command_refernce/BucketsPropertyAdd.md'
    - 'capabilities':
      - 'declare': 'somaadm/command_refernce/CapabilitiesDeclare.md'
    - 'checks':
      - 'create': 'somaadm/command_refernce/ChecksCreate.md'
      - 'delete': 'somaadm/command_refernce/ChecksDelete.md'
      - 'list': 'somaadm/command_refernce/ChecksList.md'
      - 'show': 'somaadm/command_refernce/ChecksShow.md'
    - 'servers':
      - 'create': 'somaadm/command_refernce/ServersCreate.md'
      - 'update': 'somaadm/command_refernce/ServersUpdate.md'
    - 'users':
      - 'password update': 'somaadm/command_refernce/UsersPasswordUpdate.md'
    - 'ops':
      - 'bootstrap': 'somaadm/command_refernce/OpsBootstrap.md'
      - 'dumptoken': 'somaadm/command_refernce/OpsDumptoken.md'
      - 'repository stop': 'somaadm/command_refernce/OpsRepositoryStop.md'
      - 'repository rebuild': 'somaadm/command_refernce/OpsRepositoryRebuild.md'
      - 'repository restart': 'somaadm/command_refernce/OpsRepositoryRestart.md'
