package main


func (s *supervisor) authorize(q *msg.Request) {
	result := msg.Result{Type: `supervisor`, Action: `verdict`}

	switch svPermissionActionScopeMap[q.Super.PermAction] {
	case `global`:
		result.Super = &msg.Supervisor{
			Verdict: s.authorize_global(q),
		}
	case `repository`:
	case `team`:
	default:
		goto unauthorized
	}
	q.Reply <- result
	return

unauthorized:
	result.Super = &msg.Supervisor{Verdict: 403}
	q.Reply <- result
}

func (s *supervisor) authorize_global(q *msg.Request) uint16 {
	for _, perm := range svGlobalRequiredPermission[q.Super.PermAction] {
		if userUUID, ok := s.id_user_rev.get(q.Super.PermUser); !ok {
			return 403
		}
		if permUUID, ok := s.id_permission.get(perm); !ok {
			return 403
		}
		if s.global_permissions.assess(userUUID, permUUID) {
			return 200
		}
	}
	return 403
}

var svGlobalRequiredPermission = map[string][]string{
	`attribute_create`:               []string{`system_all`},
	`attribute_delete`:               []string{`system_all`},
	`attributes_list`:                []string{`global_schema`, `system_all`},
	`attributes_show`:                []string{`global_schema`, `system_all`},
	`category_create`:                []string{`system_all`},
	`category_delete`:                []string{`system_all`},
	`category_list`:                  []string{`global_schema`, `system_all`},
	`category_show`:                  []string{`global_schema`, `system_all`},
	`datacenters_create`:             []string{`system_all`},
	`datacenters_delete`:             []string{`system_all`},
	`datacenters_list`:               []string{`global_schema`, `system_all`},
	`datacenters_rename`:             []string{`system_all`},
	`datacenters_show`:               []string{`global_schema`, `system_all`},
	`environments_create`:            []string{`system_all`},
	`environments_delete`:            []string{`system_all`},
	`environments_list`:              []string{`global_schema`, `system_all`},
	`environments_rename`:            []string{`system_all`},
	`environments_show`:              []string{`global_schema`, `system_all`},
	`levels_create`:                  []string{`system_all`},
	`levels_delete`:                  []string{`system_all`},
	`levels_list`:                    []string{`global_schema`, `system_all`},
	`levels_search`:                  []string{`global_schema`, `system_all`},
	`levels_show`:                    []string{`global_schema`, `system_all`},
	`metric_create`:                  []string{`system_all`},
	`metric_delete`:                  []string{`system_all`},
	`metrics_list`:                   []string{`global_schema`, `system_all`},
	`metrics_show`:                   []string{`global_schema`, `system_all`},
	`mode_create`:                    []string{`system_all`},
	`mode_delete`:                    []string{`system_all`},
	`modes_list`:                     []string{`global_schema`, `system_all`},
	`modes_show`:                     []string{`global_schema`, `system_all`},
	`monitoring_create`:              []string{`system_all`},
	`monitoring_delete`:              []string{`system_all`},
	`node_create`:                    []string{`system_all`},
	`node_delete`:                    []string{`system_all`},
	`oncall_create`:                  []string{`system_all`},
	`oncall_delete`:                  []string{`system_all`},
	`oncall_list`:                    []string{`global_schema`, `system_all`},
	`oncall_search`:                  []string{`global_schema`, `system_all`},
	`oncall_show`:                    []string{`global_schema`, `system_all`},
	`oncall_update`:                  []string{`system_all`},
	`permission_create`:              []string{`system_all`},
	`permission_delete`:              []string{`system_all`},
	`permission_list`:                []string{`global_schema`, `system_all`},
	`permission_show`:                []string{`global_schema`, `system_all`},
	`predicate_create`:               []string{`system_all`},
	`predicate_delete`:               []string{`system_all`},
	`predicates_list`:                []string{`global_schema`, `system_all`},
	`predicates_show`:                []string{`global_schema`, `system_all`},
	`property_native_create`:         []string{`system_all`},
	`property_native_delete`:         []string{`system_all`},
	`property_native_list`:           []string{`global_schema`, `system_all`},
	`property_native_show`:           []string{`global_schema`, `system_all`},
	`property_service_global_create`: []string{`system_all`},
	`property_service_global_delete`: []string{`system_all`},
	`property_service_global_list`:   []string{`global_schema`, `system_all`},
	`property_service_global_search`: []string{`global_schema`, `system_all`},
	`property_service_global_show`:   []string{`global_schema`, `system_all`},
	`property_system_create`:         []string{`system_all`},
	`property_system_delete`:         []string{`system_all`},
	`property_system_list`:           []string{`global_schema`, `system_all`},
	`property_system_search`:         []string{`global_schema`, `system_all`},
	`property_system_show`:           []string{`global_schema`, `system_all`},
	`provider_create`:                []string{`system_all`},
	`provider_delete`:                []string{`system_all`},
	`providers_list`:                 []string{`global_schema`, `system_all`},
	`providers_show`:                 []string{`global_schema`, `system_all`},
	`repository_create`:              []string{`system_all`},
	`repository_delete`:              []string{`system_all`},
	`server_create`:                  []string{`system_all`},
	`server_delete`:                  []string{`system_all`},
	`servers_list`:                   []string{`global_schema`, `system_all`},
	`servers_search`:                 []string{`global_schema`, `system_all`},
	`servers_show`:                   []string{`global_schema`, `system_all`},
	`states_create`:                  []string{`system_all`},
	`states_delete`:                  []string{`system_all`},
	`states_list`:                    []string{`global_schema`, `system_all`},
	`states_rename`:                  []string{`global_schema`, `system_all`},
	`states_show`:                    []string{`global_schema`, `system_all`},
	`status_create`:                  []string{`system_all`},
	`status_delete`:                  []string{`system_all`},
	`status_list`:                    []string{`global_schema`, `system_all`},
	`status_show`:                    []string{`global_schema`, `system_all`},
	`team_create`:                    []string{`system_all`},
	`team_delete`:                    []string{`system_all`},
	`team_list`:                      []string{`global_schema`, `system_all`},
	`team_search`:                    []string{`global_schema`, `system_all`},
	`team_show`:                      []string{`global_schema`, `system_all`},
	`types_create`:                   []string{`system_all`},
	`types_delete`:                   []string{`system_all`},
	`types_list`:                     []string{`global_schema`, `system_all`},
	`types_rename`:                   []string{`global_schema`, `system_all`},
	`types_show`:                     []string{`global_schema`, `system_all`},
	`unit_create`:                    []string{`system_all`},
	`unit_delete`:                    []string{`system_all`},
	`units_list`:                     []string{`global_schema`, `system_all`},
	`units_show`:                     []string{`global_schema`, `system_all`},
	`user_create`:                    []string{`system_all`},
	`user_delete`:                    []string{`system_all`},
	`users_list`:                     []string{`global_schema`, `system_all`},
	`users_search`:                   []string{`global_schema`, `system_all`},
	`users_show`:                     []string{`global_schema`, `system_all`},
	`validity_create`:                []string{`system_all`},
	`validity_delete`:                []string{`system_all`},
	`validity_list`:                  []string{`global_schema`, `system_all`},
	`validity_show`:                  []string{`global_schema`, `system_all`},
	`view_create`:                    []string{`system_all`},
	`view_delete`:                    []string{`system_all`},
	`view_list`:                      []string{`global_schema`, `system_all`},
	`view_rename`:                    []string{`system_all`},
	`view_show`:                      []string{`global_schema`, `system_all`},
}

var svPermissionActionScopeMap = map[string]string{
	`attribute_create`:               `global`,
	`attribute_delete`:               `global`,
	`attributes_list`:                `global`,
	`attributes_show`:                `global`,
	`category_create`:                `global`,
	`category_delete`:                `global`,
	`category_list`:                  `global`,
	`category_show`:                  `global`,
	`datacenters_create`:             `global`,
	`datacenters_delete`:             `global`,
	`datacenters_list`:               `global`,
	`datacenters_rename`:             `global`,
	`datacenters_show`:               `global`,
	`environments_create`:            `global`,
	`environments_delete`:            `global`,
	`environments_list`:              `global`,
	`environments_rename`:            `global`,
	`environments_show`:              `global`,
	`levels_create`:                  `global`,
	`levels_delete`:                  `global`,
	`levels_list`:                    `global`,
	`levels_search`:                  `global`,
	`levels_show`:                    `global`,
	`metric_create`:                  `global`,
	`metric_delete`:                  `global`,
	`metrics_list`:                   `global`,
	`metrics_show`:                   `global`,
	`mode_create`:                    `global`,
	`mode_delete`:                    `global`,
	`modes_list`:                     `global`,
	`modes_show`:                     `global`,
	`monitoring_create`:              `global`,
	`monitoring_delete`:              `global`,
	`node_create`:                    `global`,
	`node_delete`:                    `global`,
	`oncall_create`:                  `global`,
	`oncall_delete`:                  `global`,
	`oncall_list`:                    `global`,
	`oncall_search`:                  `global`,
	`oncall_show`:                    `global`,
	`oncall_update`:                  `global`,
	`permission_create`:              `global`,
	`permission_delete`:              `global`,
	`permission_list`:                `global`,
	`permission_show`:                `global`,
	`predicate_create`:               `global`,
	`predicate_delete`:               `global`,
	`predicates_list`:                `global`,
	`predicates_show`:                `global`,
	`property_native_create`:         `global`,
	`property_native_delete`:         `global`,
	`property_native_list`:           `global`,
	`property_native_show`:           `global`,
	`property_service_global_create`: `global`,
	`property_service_global_delete`: `global`,
	`property_service_global_list`:   `global`,
	`property_service_global_search`: `global`,
	`property_service_global_show`:   `global`,
	`property_system_create`:         `global`,
	`property_system_delete`:         `global`,
	`property_system_list`:           `global`,
	`property_system_search`:         `global`,
	`property_system_show`:           `global`,
	`provider_create`:                `global`,
	`provider_delete`:                `global`,
	`providers_list`:                 `global`,
	`providers_show`:                 `global`,
	`repository_create`:              `global`,
	`repository_delete`:              `global`,
	`server_create`:                  `global`,
	`server_delete`:                  `global`,
	`servers_list`:                   `global`,
	`servers_search`:                 `global`,
	`servers_show`:                   `global`,
	`states_create`:                  `global`,
	`states_delete`:                  `global`,
	`states_list`:                    `global`,
	`states_rename`:                  `global`,
	`states_show`:                    `global`,
	`status_create`:                  `global`,
	`status_delete`:                  `global`,
	`status_list`:                    `global`,
	`status_show`:                    `global`,
	`team_create`:                    `global`,
	`team_delete`:                    `global`,
	`team_list`:                      `global`,
	`team_search`:                    `global`,
	`team_show`:                      `global`,
	`types_create`:                   `global`,
	`types_delete`:                   `global`,
	`types_list`:                     `global`,
	`types_rename`:                   `global`,
	`types_show`:                     `global`,
	`unit_create`:                    `global`,
	`unit_delete`:                    `global`,
	`units_list`:                     `global`,
	`units_show`:                     `global`,
	`user_create`:                    `global`,
	`user_delete`:                    `global`,
	`users_list`:                     `global`,
	`users_search`:                   `global`,
	`users_show`:                     `global`,
	`validity_create`:                `global`,
	`validity_delete`:                `global`,
	`validity_list`:                  `global`,
	`validity_show`:                  `global`,
	`view_create`:                    `global`,
	`view_delete`:                    `global`,
	`view_list`:                      `global`,
	`view_rename`:                    `global`,
	`view_show`:                      `global`,
	`bucket_create`:                  `repository`,
	`bucket_property_add`:            `repository`,
	`buckets_list`:                   `repository`,
	`buckets_search`:                 `repository`,
	`buckets_show`:                   `repository`,
	`check_create`:                   `repository`,
	`checks_list`:                    `repository`,
	`checks_search`:                  `repository`,
	`checks_show`:                    `repository`,
	`cluster_create`:                 `repository`,
	`cluster_member_add`:             `repository`,
	`cluster_property_add`:           `repository`,
	`clusters_list`:                  `repository`,
	`clusters_members_list`:          `repository`,
	`clusters_search`:                `repository`,
	`clusters_show`:                  `repository`,
	`group_create`:                   `repository`,
	`group_member_add`:               `repository`,
	`group_property_add`:             `repository`,
	`groups_list`:                    `repository`,
	`groups_members_list`:            `repository`,
	`groups_search`:                  `repository`,
	`groups_show`:                    `repository`,
	`node_property_add`:              `repository`,
	`property_custom_create`:         `repository`,
	`property_custom_delete`:         `repository`,
	`property_custom_list`:           `repository`,
	`property_custom_search`:         `repository`,
	`property_custom_show`:           `repository`,
	`repository_list`:                `repository`,
	`repository_search`:              `repository`,
	`repository_show`:                `repository`,
	`node_list`:                      `team`,
	`node_search`:                    `team`,
	`node_show`:                      `team`,
	`node_show_config`:               `team`,
	`property_service_team_list`:     `team`,
	`property_service_team_search`:   `team`,
	`property_service_team_show`:     `team`,
	`property_service_team_create`:   `team`,
	`property_service_team_delete`:   `team`,
}

// vim: ts=4 sw=4 sts=4 noet fenc=utf-8 ffs=unix
